version: '3.7'
services:
  kosongan:
    environment:
      - PORT=6969
    image: edo/kosongan:1.0
    build:
      context: ./
      dockerfile: dockerfile
    ports: 
      - "8969:6969"
    restart: always
